export default [
    {label: '爱情', value: '爱情'},
    {label: '剧情', value: '剧情'},
    {label: '喜剧', value: '喜剧'},
    {label: '家庭', value: '家庭'},
    {label: '文艺', value: '文艺'},
    {label: '音乐', value: '音乐'},
    {label: '歌舞', value: '歌舞'},
    {label: '动漫', value: '动漫'},
    {label: '武侠', value: '武侠'},
    {label: '动作', value: '动作'},
    {label: '恐怖', value: '恐怖'},
    {label: '冒险', value: '冒险'},
    {label: '犯罪', value: '犯罪'},
    {label: '悬疑', value: '悬疑'},
    {label: '记录', value: '记录'},
    {label: '战争', value: '战争'},
    {label: '惊悚', value: '惊悚'},
    {label: '科幻', value: '科幻'},
    {label: '历史', value: '历史'},
    {label: '传记', value: '传记'},
]
